"""Project-wide constants."""

WORKSHEET_NAMES = (
    "SUMMARY",
    "MATCHED_BENZARA",
    "PRICE_UPDATE_PASS",
    "NEW_BENZARA_PASS",
    "NEW_BENZARA_REVIEW",
    "HOLD_LOGISTICS",
    "OUT_OF_STOCK",
    "ORPHAN_STORE",
    "OTHER_SUPPLIER",
    "CONFLICTS",
    "RULES_AND_CONFIG",
)

MATCH_STATUSES = (
    "MATCHED_BENZARA",
    "NEW_BENZARA",
    "ORPHAN_STORE",
    "OTHER_SUPPLIER",
    "CONFLICT",
)

LOGISTICS_STATUSES = (
    "PASS_LOGISTICS",
    "REVIEW_LOGISTICS",
    "HOLD_LOGISTICS",
)

CATALOG_DECISIONS = (
    "PASS",
    "REVIEW",
    "HOLD_LOGISTICS",
    "OUT_OF_STOCK",
    "ORPHAN",
    "OTHER_SUPPLIER",
    "CONFLICT",
)

