"""Project-wide constants."""

WORKSHEET_NAMES = (
    "SUMMARY",
    "MATCHED_BENZARA",
    "PRICE_UPDATE_PASS",
    "PRICE_UPDATE_EXCLUDED",
    "AUTO_PASS",
    "AUTO_HOLD_LOGISTICS",
    "AUTO_HOLD_OUT_OF_STOCK",
    "AUTO_ARCHIVE_ORPHAN_CANDIDATES",
    "KEEP_OUTSIDE_BENZARA_FLOW",
    "CORE_CANDIDATES",
    "NEW_BENZARA_PASS",
    "NEW_BENZARA_REVIEW",
    "HOLD_LOGISTICS",
    "OUT_OF_STOCK",
    "ORPHAN_STORE",
    "OTHER_SUPPLIER",
    "CONFLICTS",
    "DATA_QUALITY",
    "SUPPLIER_CLASSIFICATION",
    "LOGISTICS_DIAGNOSTICS",
    "RULES_AND_CONFIG",
)

AUTO_HOLD_WORKSHEET_NAMES = (
    "SUMMARY",
    "AUTO_HOLD_LOGISTICS",
    "AUTO_HOLD_OUT_OF_STOCK",
    "AUTO_ARCHIVE_ORPHAN_CANDIDATES",
    "KEEP_OUTSIDE_BENZARA_FLOW",
)

CORE_CANDIDATES_WORKSHEET_NAMES = (
    "CORE_CANDIDATES",
)

MANUAL_REVIEW_SHEET_NAME = "MANUAL_REVIEW"

MATCH_STATUSES = (
    "MATCHED_BENZARA",
    "NEW_BENZARA",
    "ORPHAN_STORE",
    "OTHER_SUPPLIER",
    "CONFLICT",
)

LOGISTICS_STATUSES = (
    "PASS_LOGISTICS",
    "REVIEW_LOGISTICS",
    "HOLD_LOGISTICS",
)

COMMERCIAL_STATUSES = (
    "PRICE_READY",
    "PRICE_REVIEW",
    "OUT_OF_STOCK",
    "ORPHAN",
    "OTHER_SUPPLIER",
    "CONFLICT",
    "MISSING_DATA",
)

CATALOG_DECISIONS = (
    "PASS",
    "REVIEW",
    "HOLD_LOGISTICS",
    "OUT_OF_STOCK",
    "ORPHAN",
    "OTHER_SUPPLIER",
    "CONFLICT",
)

PRICE_UPDATE_STATUSES = (
    "PRICE_READY",
    "EXCLUDED_OUT_OF_STOCK",
    "EXCLUDED_HOLD_LOGISTICS",
    "EXCLUDED_REVIEW_LOGISTICS",
    "EXCLUDED_MISSING_BENZARA_PRICE",
    "EXCLUDED_INVALID_BENZARA_PRICE",
    "EXCLUDED_BUNDLE_PRODUCT",
    "EXCLUDED_MISSING_SKU",
    "EXCLUDED_CONFLICT",
    "EXCLUDED_OTHER",
)

DATA_QUALITY_STATUSES = (
    "OK",
    "REVIEW",
    "CRITICAL",
)

SUPPLIER_CLASSIFICATIONS = (
    "BENZARA_MATCHED",
    "BENZARA_ORPHAN_SUSPECTED",
    "OTHER_SUPPLIER_CONFIRMED",
    "UNKNOWN_SUPPLIER",
)

RECOMMENDED_OPERATIONAL_ACTIONS = (
    "AUTO_PASS",
    "AUTO_HOLD_LOGISTICS",
    "AUTO_HOLD_OUT_OF_STOCK",
    "AUTO_ARCHIVE_ORPHAN_CANDIDATE",
    "KEEP_OUTSIDE_BENZARA_FLOW",
    "MANUAL_REVIEW_HIGH",
    "MANUAL_REVIEW_MEDIUM",
    "MANUAL_REVIEW_LOW",
)
